### PR TITLE
Update to 1.19.4

### PR DESCRIPTION
**Pull request by QuentiumYT**
Based on your work in 1.19.2 and 1.19.3 branches, I updated the project for 1.19.4

I'm unsure about the tick override but it caused some troubles with an ingame crash

Every method is ported to 1.19.4 latest mappings and I bumped all versions

Tested ingame with several items and works fine.

PS: It would be better to have a brand new '1.19' branch so I can merge this properly onto the new major MC version

### CODE REVIEW

**Comment by yzl210** [comment]
You should target the 1.19.3 branch

**Comment by QuentiumYT** [comment]
> You should target the 1.19.3 branch

Alright will do that, note that it will merge onto your 1.19.3 commit that I "reverted" to base my branch :)

**Comment by QuentiumYT** [comment]
This is what I was thinking, if you want to merge onto 1.19.2, I will rebase on my side, but you merged an other commit since then ^^'
What do you prefer?

**Comment by yzl210** [comment]
I renamed the 1.19.3 branch to 1.19.4, target that

**Comment by QuentiumYT** [comment]
Had to merge manually because as I said, I started from the 1.18 branch.
A bit less clean but whatever, this is now complete

**Comment by QuentiumYT** [comment]
Any update on this? :)

**Pull request merged**
