### PR TITLE
Fixes to 4.0.2 and 4.0.1

### PR DESCRIPTION
**Pull request by zTotto**
4.0.2 would not start with REI and REI plugin compatibilities.
4.0.1 would crash when adding fluids recipes

### CODE REVIEW

**Comment by yzl210** [comment]
The tick method was not final because of access widener (transformer), and I switched to use `containerTick` in 1.20.

**Comment by zTotto** [comment]
Overriding tick() made the game not load at all, i'll check if i can use containerTick in any way

**Comment by yzl210** [comment]
Yeah, there's a bug with arch loom that it doesn't remap the tick in access widener to obfuscated name, so it's not working, I did that manually

**Comment by zTotto** [comment]
Ok i readded the tick method, i also wanted to ask if you could upload one of this fixed versions to curseforge so that modpack makers can use this 1.18 version with working fluid recipes (if you see a lot more lines is because my vscode decided to format JecaGui.java lmao)

**Comment by yzl210** [comment]
Yeah I'll do that after I backport all the fixes from 1.20

**Pull request merged**
