### PR TITLE
Improve performance of Context::matches

### LINKED ISSUE #99: Performance issues when there is many ingredients for a recipe
I tried to break down the Vending Upgrade in Omnifactory, just to see what is required. But once the number of ingredients is greater than a hundred or slow, the calculator would be very slow. It would take around 5 seconds to load or close, or to import any new recipes. However, if I switched to a new recipe, the issues were gone. Gameplay was not otherwise affected.

### PR DESCRIPTION
**Pull request by Fybe**
Look up matching items in the registry instead of searching linearly through ALL registered items. This speeds up CostList merging. Cost calculation now only takes milliseconds instead of seconds for complex recipes.

Fixes #99 and #126.

### CODE REVIEW

**Comment by yzl210** [comment]
Thanks!

**Comment by Gschmidt22** [comment]
Is there any chance of this fix being backported to older versions of the mod? This mod helps immensely with older expert packs but the freeze described in #99 can last up to 10 or 15 seconds when opening the calculator on more complex recipes.

**Comment by Fybe** [comment]
If you tell me which version of minecraft you are interested in, I can create a pull request for that specific version.

Otherwise, I would have to bombard this repo with PRs for each version branch. Ideally the commit should just be cherry picked into all the version branches, but doing so cannot be done without write permission afaik.

**Comment by Gschmidt22** [comment]
I'm using Minecraft 1.12.2, running Enigmatica 2 Expert Skyblock currently with a mod version: 3.2.7
Thank you! I appreciate you taking the time.

**Comment by Fybe** [comment]
I think [this](https://github.com/Fybe/JustEnoughCalculation/releases/tag/1.12-lag-fix) should work.

**Pull request merged**
